FROM captvty3-wine-patcher:no-ngen

USER root

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      gdb \
      strace \
      procps \
      lsof \
      file \
      binutils \
      iproute2 \
 && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/bin/bash"]
